
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Firebase Auth test application.

target 'integration_test' do
  pod 'Firebase/Auth', '6.24.0'
end

post_install do |installer|
  system("/usr/bin/python ./download_googletest.py")
end

