source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'GetPods' do
  pod 'Firebase/Core', '10.16.0'

  pod 'Google-Mobile-Ads-SDK', '10.12.0'
  pod 'GoogleUserMessagingPlatform', '2.1.0'
  pod 'Firebase/Analytics', '10.16.0'
  pod 'Firebase/AppCheck', '10.16.0'
  pod 'Firebase/Auth', '10.16.0'
  pod 'Firebase/Crashlytics', '10.16.0'
  pod 'Firebase/Database', '10.16.0'
  pod 'Firebase/DynamicLinks', '10.16.0'
  pod 'Firebase/Firestore', '10.16.0'
  pod 'Firebase/Functions', '10.16.0'
  pod 'Firebase/Installations', '10.16.0'
  pod 'Firebase/Messaging', '10.16.0'
  pod 'Firebase/RemoteConfig', '10.16.0'
  pod 'Firebase/Storage', '10.16.0'

end
