source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'GetPods' do
  pod 'Firebase/Core', '9.0.0'

  pod 'Google-Mobile-Ads-SDK', '9.4.0'
  pod 'Firebase/Analytics', '9.0.0'
  pod 'Firebase/Auth', '9.0.0'
  pod 'Firebase/Crashlytics', '9.0.0'
  pod 'Firebase/Database', '9.0.0'
  pod 'Firebase/DynamicLinks', '9.0.0'
  pod 'Firebase/Firestore', '9.0.0'
  pod 'Firebase/Functions', '9.0.0'
  pod 'Firebase/Installations', '9.0.0'
  pod 'Firebase/Messaging', '9.0.0'
  pod 'Firebase/RemoteConfig', '9.0.0'
  pod 'Firebase/Storage', '9.0.0'

end
