source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
# Firebase App test application.
use_frameworks! :linkage => :static

target 'integration_test' do
  pod 'Firebase/Analytics', '10.9.0'
end

post_install do |installer|
  # If this is running from inside the SDK directory, run the setup script.
  system("if [[ -r ../../setup_integration_tests.py ]]; then python3 ../../setup_integration_tests.py .; fi")
  system("python3 ./download_googletest.py")
end

