-ignorewarnings
-keep,includedescriptorclasses public class com.google.firebase.example.LoggingUtils { * ; }
-keep,includedescriptorclasses public class com.google.android.gms.tasks.CancellationTokenSource { * ; }
-keep,includedescriptorclasses public class com.google.android.gms.tasks.TaskCompletionSource { * ; }
