source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
# Firebase AdMob test application.

target 'integration_test' do
  pod 'Firebase/Analytics', '8.6.0'
  pod 'Google-Mobile-Ads-SDK', '7.69.0-cppsdk'
end

post_install do |installer|
  # If this is running from inside the SDK directory, run the setup script.
  system("if [[ -r ../../setup_integration_tests.py ]]; then python ../../setup_integration_tests.py .; fi")
  system("/usr/bin/python ./download_googletest.py")
end

