
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Firebase AdMob test application.

target 'integration_test' do
  pod 'Firebase/AdMob', '6.24.0'
end

post_install do |installer|
  # If this is running from inside the SDK directory, run the setup script.
  system("if [[ -r ../../setup_integration_tests.py ]]; then python ../../setup_integration_tests.py .; fi")
  system("/usr/bin/python ./download_googletest.py")
end

