/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef FIREBASE_AI_SRC_INCLUDE_FIREBASE_AI_MODEL_CONTENT_H_
#define FIREBASE_AI_SRC_INCLUDE_FIREBASE_AI_MODEL_CONTENT_H_

#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include "firebase/ai/types.h"
#include "firebase/variant.h"

namespace firebase {
namespace ai {

/// @brief Represents a text part of a `ModelContent` message.
struct TextPart {
  /// @brief Default constructor.
  TextPart() {}

  /// @brief Construct a TextPart with the given text.
  ///
  /// @param text The text content.
  explicit TextPart(const std::string& text) : text(text) {}

  /// @brief The text content.
  std::string text;
};

/// @brief Data with a specified media (MIME) type, sent inline in the payload.
struct InlineDataPart {
  /// @brief Default constructor.
  InlineDataPart() {}

  /// @brief Construct an InlineDataPart from raw bytes.
  ///
  /// @param mime_type The IANA standard MIME type (e.g. `"image/jpeg"`).
  /// @param data The raw binary payload bytes.
  InlineDataPart(const std::string& mime_type, const std::vector<uint8_t>& data)
      : mime_type(mime_type), data(data) {}

  /// @brief Construct an InlineDataPart from a raw byte pointer and length.
  ///
  /// @param mime_type The IANA standard MIME type.
  /// @param bytes Pointer to the binary data.
  /// @param size Number of bytes.
  InlineDataPart(const std::string& mime_type, const uint8_t* bytes,
                 size_t size)
      : mime_type(mime_type), data(bytes, bytes + size) {}

  /// @brief The IANA standard MIME type of the data.
  std::string mime_type;

  /// @brief The raw binary data.
  std::vector<uint8_t> data;
};

/// @brief Data referenced via a URI (such as a Cloud Storage `gs://` URI or
/// HTTP/HTTPS URL) with a specified media (MIME) type.
struct FileDataPart {
  /// @brief Default constructor.
  FileDataPart() {}

  /// @brief Construct a FileDataPart with the given MIME type and URI.
  ///
  /// @param mime_type The IANA standard MIME type.
  /// @param uri The URI or URL of the file.
  FileDataPart(const std::string& mime_type, const std::string& uri)
      : mime_type(mime_type), uri(uri) {}

  /// @brief The IANA standard MIME type of the file.
  std::string mime_type;

  /// @brief The URI or URL of the file.
  std::string uri;
};

/// @brief A predicted function call returned from the model.
struct FunctionCallPart {
  /// @brief Default constructor.
  FunctionCallPart() {}

  /// @brief Construct a FunctionCallPart.
  ///
  /// @param name The name of the function to call.
  /// @param args The function arguments as a map of parameter names to Variant
  /// values.
  /// @param id Optional unique identifier for the function call.
  FunctionCallPart(const std::string& name,
                   const std::map<std::string, Variant>& args,
                   const Optional<std::string>& id = Optional<std::string>())
      : name(name), args(args), id(id) {}

  /// @brief The name of the function to call.
  std::string name;

  /// @brief The function arguments as key-value pairs.
  std::map<std::string, Variant> args;

  /// @brief Optional unique identifier for this function call.
  Optional<std::string> id;
};

/// @brief Result output from a `FunctionCallPart` passed back to the model.
struct FunctionResponsePart {
  /// @brief Default constructor.
  FunctionResponsePart() {}

  /// @brief Construct a FunctionResponsePart.
  ///
  /// @param name The name of the function that was called.
  /// @param response The structured response data returned by the function.
  /// @param id Optional identifier matching the corresponding
  /// `FunctionCallPart::id`.
  FunctionResponsePart(
      const std::string& name, const std::map<std::string, Variant>& response,
      const Optional<std::string>& id = Optional<std::string>())
      : name(name), response(response), id(id) {}

  /// @brief The name of the function that was called.
  std::string name;

  /// @brief The function response fields.
  std::map<std::string, Variant> response;

  /// @brief Optional identifier of the corresponding function call.
  Optional<std::string> id;
};

/// @brief Code generated by the model that is meant to be executed by the
/// backend.
struct ExecutableCodePart {
  /// @brief Programming language of the executable code.
  enum CodeLanguage {
    /// Unspecified or unrecognized language.
    kLanguageUnspecified = 0,
    /// Python.
    kLanguagePython = 1,
  };

  /// @brief Default constructor.
  ExecutableCodePart() : language(kLanguageUnspecified) {}

  /// @brief Construct an ExecutableCodePart.
  ///
  /// @param language The programming language.
  /// @param code The source code to execute.
  ExecutableCodePart(CodeLanguage language, const std::string& code)
      : language(language), code(code) {}

  /// @brief The programming language of the `code`.
  CodeLanguage language;

  /// @brief The source code to be executed.
  std::string code;
};

/// @brief Represents the result of executing an `ExecutableCodePart` on the
/// backend.
struct CodeExecutionResultPart {
  /// @brief Default constructor.
  CodeExecutionResultPart() : outcome(kCodeExecutionOutcomeUnspecified) {}

  /// @brief Construct a CodeExecutionResultPart.
  ///
  /// @param outcome Outcome of the code execution.
  /// @param output Captured stdout or stderr from the execution.
  CodeExecutionResultPart(CodeExecutionOutcome outcome,
                          const std::string& output)
      : outcome(outcome), output(output) {}

  /// @brief Outcome of the code execution.
  CodeExecutionOutcome outcome;

  /// @brief Captured stdout (if successful) or stderr/error description.
  std::string output;
};

/// @brief A discrete piece of data in a `ModelContent` message (text, inline
/// binary data, file reference, function call, function response, or code
/// execution data).
///
/// Mirrors `ModelContent.Part` in the Unity SDK and `Part` in the Flutter SDK.
class Part {
 public:
  /// @brief Discriminator for the active variant held by a `Part`.
  enum Kind {
    /// Empty or uninitialized part.
    kKindNone = 0,
    /// Text part (`TextPart`).
    kKindText,
    /// Inline binary data part (`InlineDataPart`).
    kKindInlineData,
    /// File URI reference part (`FileDataPart`).
    kKindFileData,
    /// Function call part (`FunctionCallPart`).
    kKindFunctionCall,
    /// Function response part (`FunctionResponsePart`).
    kKindFunctionResponse,
    /// Executable code part (`ExecutableCodePart`).
    kKindExecutableCode,
    /// Code execution result part (`CodeExecutionResultPart`).
    kKindCodeExecutionResult,
  };

  /// @brief Default constructor creates an empty Part.
  Part() : kind_(kKindNone), is_thought_(false) {}

  /// @brief Construct a Part from a `TextPart`.
  Part(const TextPart& part, bool is_thought = false,  // NOLINT
       const Optional<std::string>& thought_signature = Optional<std::string>())
      : kind_(kKindText),
        text_part_(part),
        is_thought_(is_thought),
        thought_signature_(thought_signature) {}

  /// @brief Construct a Part from a string (creates a `TextPart`).
  Part(const std::string& text)  // NOLINT
      : kind_(kKindText), text_part_(text), is_thought_(false) {}

  /// @brief Construct a Part from a C-string (creates a `TextPart`).
  Part(const char* text)  // NOLINT
      : kind_(kKindText), text_part_(text ? text : ""), is_thought_(false) {}

  /// @brief Construct a Part from an `InlineDataPart`.
  Part(const InlineDataPart& part, bool is_thought = false,  // NOLINT
       const Optional<std::string>& thought_signature = Optional<std::string>())
      : kind_(kKindInlineData),
        inline_data_part_(part),
        is_thought_(is_thought),
        thought_signature_(thought_signature) {}

  /// @brief Construct a Part from a `FileDataPart`.
  Part(const FileDataPart& part, bool is_thought = false,  // NOLINT
       const Optional<std::string>& thought_signature = Optional<std::string>())
      : kind_(kKindFileData),
        file_data_part_(part),
        is_thought_(is_thought),
        thought_signature_(thought_signature) {}

  /// @brief Construct a Part from a `FunctionCallPart`.
  Part(const FunctionCallPart& part, bool is_thought = false,  // NOLINT
       const Optional<std::string>& thought_signature = Optional<std::string>())
      : kind_(kKindFunctionCall),
        function_call_part_(part),
        is_thought_(is_thought),
        thought_signature_(thought_signature) {}

  /// @brief Construct a Part from a `FunctionResponsePart`.
  Part(const FunctionResponsePart& part, bool is_thought = false,  // NOLINT
       const Optional<std::string>& thought_signature = Optional<std::string>())
      : kind_(kKindFunctionResponse),
        function_response_part_(part),
        is_thought_(is_thought),
        thought_signature_(thought_signature) {}

  /// @brief Construct a Part from an `ExecutableCodePart`.
  Part(const ExecutableCodePart& part, bool is_thought = false,  // NOLINT
       const Optional<std::string>& thought_signature = Optional<std::string>())
      : kind_(kKindExecutableCode),
        executable_code_part_(part),
        is_thought_(is_thought),
        thought_signature_(thought_signature) {}

  /// @brief Construct a Part from a `CodeExecutionResultPart`.
  Part(const CodeExecutionResultPart& part, bool is_thought = false,  // NOLINT
       const Optional<std::string>& thought_signature = Optional<std::string>())
      : kind_(kKindCodeExecutionResult),
        code_execution_result_part_(part),
        is_thought_(is_thought),
        thought_signature_(thought_signature) {}

  /// @brief Returns the active kind of this Part.
  Kind kind() const { return kind_; }

  /// @brief Returns true if this is a `TextPart`.
  bool is_text() const { return kind_ == kKindText; }
  /// @brief Returns true if this is an `InlineDataPart`.
  bool is_inline_data() const { return kind_ == kKindInlineData; }
  /// @brief Returns true if this is a `FileDataPart`.
  bool is_file_data() const { return kind_ == kKindFileData; }
  /// @brief Returns true if this is a `FunctionCallPart`.
  bool is_function_call() const { return kind_ == kKindFunctionCall; }
  /// @brief Returns true if this is a `FunctionResponsePart`.
  bool is_function_response() const { return kind_ == kKindFunctionResponse; }
  /// @brief Returns true if this is an `ExecutableCodePart`.
  bool is_executable_code() const { return kind_ == kKindExecutableCode; }
  /// @brief Returns true if this is a `CodeExecutionResultPart`.
  bool is_code_execution_result() const {
    return kind_ == kKindCodeExecutionResult;
  }

  /// @brief Returns the `TextPart` content.
  const TextPart& text_part() const { return text_part_; }
  /// @brief Returns the `InlineDataPart` content.
  const InlineDataPart& inline_data_part() const { return inline_data_part_; }
  /// @brief Returns the `FileDataPart` content.
  const FileDataPart& file_data_part() const { return file_data_part_; }
  /// @brief Returns the `FunctionCallPart` content.
  const FunctionCallPart& function_call_part() const {
    return function_call_part_;
  }
  /// @brief Returns the `FunctionResponsePart` content.
  const FunctionResponsePart& function_response_part() const {
    return function_response_part_;
  }
  /// @brief Returns the `ExecutableCodePart` content.
  const ExecutableCodePart& executable_code_part() const {
    return executable_code_part_;
  }
  /// @brief Returns the `CodeExecutionResultPart` content.
  const CodeExecutionResultPart& code_execution_result_part() const {
    return code_execution_result_part_;
  }

  /// @brief Indicates whether this `Part` is a summary of the model's internal
  /// thinking process.
  bool is_thought() const { return is_thought_; }
  /// @brief Sets whether this `Part` is a thought summary.
  void set_is_thought(bool is_thought) { is_thought_ = is_thought; }

  /// @brief Returns the opaque thought signature associated with this part, if
  /// any (must be preserved when sending history back to the model).
  const Optional<std::string>& thought_signature() const {
    return thought_signature_;
  }
  /// @brief Sets the opaque thought signature associated with this part.
  void set_thought_signature(const std::string& signature) {
    thought_signature_ = signature;
  }

 private:
  Kind kind_;
  TextPart text_part_;
  InlineDataPart inline_data_part_;
  FileDataPart file_data_part_;
  FunctionCallPart function_call_part_;
  FunctionResponsePart function_response_part_;
  ExecutableCodePart executable_code_part_;
  CodeExecutionResultPart code_execution_result_part_;
  bool is_thought_;
  Optional<std::string> thought_signature_;
};

/// @brief A single message turn in a conversation with a generative model,
/// consisting of a role (`"user"`, `"model"`, or `"system"`) and one or more
/// `Part` objects.
///
/// Mirrors `Firebase.AI.ModelContent` in Unity and `Content` in Flutter.
class ModelContent {
 public:
  /// @brief Default constructor creates a `"user"` message with no parts.
  ModelContent() : role_("user") {}

  /// @brief Construct a `ModelContent` with the default `"user"` role and the
  /// given parts.
  ///
  /// @param parts The parts that make up the message.
  explicit ModelContent(const std::vector<Part>& parts)
      : role_("user"), parts_(parts) {}

  /// @brief Construct a `ModelContent` with an explicit role and parts.
  ///
  /// @param role The producer role (`"user"`, `"model"`, `"system"`, or
  /// `"function"`).
  /// @param parts The parts that make up the message.
  ModelContent(const std::string& role, const std::vector<Part>& parts)
      : role_(role.empty() ? "user" : role), parts_(parts) {}

  /// @brief Creates a `ModelContent` with a single `TextPart` and the `"user"`
  /// role.
  ///
  /// @param text The text prompt.
  /// @return A user `ModelContent` containing `text`.
  static ModelContent Text(const std::string& text);

  /// @brief Creates a `ModelContent` with a single `InlineDataPart` and the
  /// `"user"` role.
  ///
  /// @param mime_type The IANA MIME type of the data.
  /// @param data The raw binary data.
  /// @return A user `ModelContent` containing the inline data.
  static ModelContent InlineData(const std::string& mime_type,
                                 const std::vector<uint8_t>& data);

  /// @brief Creates a `ModelContent` with a single `InlineDataPart` from a byte
  /// pointer and size.
  ///
  /// @param mime_type The IANA MIME type of the data.
  /// @param bytes Pointer to the binary data.
  /// @param size Number of bytes.
  /// @return A user `ModelContent` containing the inline data.
  static ModelContent InlineData(const std::string& mime_type,
                                 const uint8_t* bytes, size_t size);

  /// @brief Creates a `ModelContent` with a single `FileDataPart` and the
  /// `"user"` role.
  ///
  /// @param mime_type The IANA MIME type of the referenced file.
  /// @param uri The URI or URL of the file.
  /// @return A user `ModelContent` containing the file reference.
  static ModelContent FileData(const std::string& mime_type,
                               const std::string& uri);

  /// @brief Creates a `ModelContent` with a single `FunctionResponsePart` and
  /// the `"user"` role.
  ///
  /// @param name The name of the function that was called.
  /// @param response The function response map.
  /// @param id Optional identifier matching `FunctionCallPart::id`.
  /// @return A user `ModelContent` containing the function response.
  static ModelContent FunctionResponse(
      const std::string& name, const std::map<std::string, Variant>& response,
      const Optional<std::string>& id = Optional<std::string>());

  /// @brief Creates a `ModelContent` with multiple `FunctionResponsePart` items
  /// and the `"user"` role.
  ///
  /// @param responses The function response parts.
  /// @return A user `ModelContent` containing all the function responses.
  static ModelContent FunctionResponses(
      const std::vector<FunctionResponsePart>& responses);

  /// @brief Creates a `ModelContent` with the `"system"` role for system
  /// instructions.
  ///
  /// @param text The system instruction text.
  /// @return A system `ModelContent`.
  static ModelContent System(const std::string& text);

  /// @brief Creates a `ModelContent` with the `"user"` role and a single text
  /// part.
  ///
  /// @param text The user message text.
  /// @return A user `ModelContent`.
  static ModelContent User(const std::string& text);

  /// @brief Creates a `ModelContent` with the `"user"` role and the given
  /// parts.
  ///
  /// @param parts The parts of the user message.
  /// @return A user `ModelContent`.
  static ModelContent User(const std::vector<Part>& parts);

  /// @brief Creates a `ModelContent` with the `"model"` role and a single text
  /// part.
  ///
  /// @param text The model message text.
  /// @return A model `ModelContent`.
  static ModelContent Model(const std::string& text);

  /// @brief Creates a `ModelContent` with the `"model"` role and the given
  /// parts.
  ///
  /// @param parts The parts of the model message.
  /// @return A model `ModelContent`.
  static ModelContent Model(const std::vector<Part>& parts);

  /// @brief Returns the role of the producer of the content.
  const std::string& role() const { return role_; }
  /// @brief Sets the role of the producer of the content.
  void set_role(const std::string& role) { role_ = role; }

  /// @brief Returns the ordered list of parts in this content.
  const std::vector<Part>& parts() const { return parts_; }
  /// @brief Returns a mutable reference to the ordered list of parts.
  std::vector<Part>& parts() { return parts_; }
  /// @brief Sets the ordered list of parts in this content.
  void set_parts(const std::vector<Part>& parts) { parts_ = parts; }

  /// @brief Appends a `Part` to this `ModelContent`.
  ///
  /// @param part The part to append.
  void AddPart(const Part& part) { parts_.push_back(part); }

 private:
  std::string role_;
  std::vector<Part> parts_;
};

}  // namespace ai
}  // namespace firebase

#endif  // FIREBASE_AI_SRC_INCLUDE_FIREBASE_AI_MODEL_CONTENT_H_
