source 'https://github.com/CocoaPods/Specs.git'
# Firebase App Check test application.
use_frameworks! :linkage => :static

target 'integration_test' do
  platform :ios, '15.0'
  pod 'Firebase/AppCheck', '12.0.0'
  pod 'Firebase/Database', '12.0.0'
  pod 'Firebase/Auth', '12.0.0'
  pod 'Firebase/Storage', '12.0.0'
  pod 'Firebase/Functions', '12.0.0'
end

target 'integration_test_tvos' do
  platform :tvos, '15.0'
  pod 'Firebase/AppCheck', '12.0.0'
  pod 'Firebase/Database', '12.0.0'
  pod 'Firebase/Auth', '12.0.0'
  pod 'Firebase/Storage', '12.0.0'
  pod 'Firebase/Functions', '12.0.0'
end

post_install do |installer|
  # If this is running from inside the SDK directory, run the setup script.
  system("if [[ -r ../../setup_integration_tests.py ]]; then python3 ../../setup_integration_tests.py .; fi")
  system("python3 ./download_googletest.py")
end

