
source 'https://github.com/CocoaPods/Specs.git'
# Firebase Realtime Database test application.

target 'integration_test' do
  platform :ios, '10.0'
  pod 'Firebase/Database', '8.6.0'
  pod 'Firebase/Auth', '8.6.0'
end

target 'integration_test_tvos' do
  platform :tvos, '10.0'
  pod 'Firebase/Database', '8.6.0'
  pod 'Firebase/Auth', '8.6.0'
end

post_install do |installer|
  # If this is running from inside the SDK directory, run the setup script.
  system("if [[ -r ../../setup_integration_tests.py ]]; then python ../../setup_integration_tests.py .; fi")
  system("/usr/bin/python ./download_googletest.py")
end

