name: Android Builds

on:
  push:    
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: build-linux-no-test
    steps:
      - uses: actions/checkout@v2
      - name: Install abysl and protobuf-compiler for python
        run: |
          python -m pip install --upgrade pip
          pip install absl-py
          sudo apt-get install python-protobuf
      - name: Install protobuf native compiler
        run: sudo apt-get install protobuf-compiler
      - name: Build Android
        run: |
           set -e
           set -x
           ./gradlew build
