name: Check PR Labels
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
    

jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
    - uses: danielchabr/pr-labels-checker@v3
      if: github.base_ref == 'main'
      with:
        hasNone: 'tests: failed, tests: in-progress'
        githubToken: ${{ github.token }}
