name: Check PR Labels
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

env:
  triggerLabelFull: "tests-requested: full"
  triggerLabelQuick: "tests-requested: quick"
  statusLabelInProgress: "tests: in-progress"
  statusLabelFailed: "tests: failed"

jobs:
  check_integration_test_labels:
    # This check fails if integration tests are queued, in progress, or failed.
    runs-on: ubuntu-latest
    steps:
    - uses: docker://agilepathway/pull-request-label-checker:latest
      # Uncomment the below line if you want this check to only be on the main branch.
      # if: github.base_ref == 'main'
      with:
        none_of: "${{ env.statusLabelInProgress }},${{ env.statusLabelFailed }},${{ env.triggerLabelFull }},${{ env.triggerLabelQuick }}"
        repo_token: ${{ github.token }}
