name: Retry Test Failures
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID to check and retry'
        default: ''
        required: true

jobs:
  check_results_and_retry_if_needed:
    name: check-results-and-retry-if-needed
    runs-on: ubuntu-22.04
    steps:
      - name: Get token for firebase-workflow-trigger
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # ratchet:actions/create-github-app-token@v1
        id: generate-token
        with:
          client-id: ${{ secrets.WORKFLOW_TRIGGER_CLIENT_ID }}
          private-key: ${{ secrets.WORKFLOW_TRIGGER_APP_PRIVATE_KEY }}
          permission-actions: write

      - name: Setup python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # ratchet:actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
        with:
          ref: ${{ matrix.branch_name }}
          fetch-depth: 0
          submodules: false
          persist-credentials: false

      - name: Install prerequisites
        run: |
          python scripts/gha/install_prereqs_desktop.py
          python -m pip install requests

      - name: Wait 3 minutes for run to finish
        run: |
          sleep 180

      - name: Run test failure retry script
        run: |
          python scripts/gha/retry_test_failures.py --token "${STEPS_GENERATE_TOKEN_OUTPUTS_TOKEN}" --run_id "${GITHUB_EVENT_INPUTS_RUN_ID}"
        env:
          STEPS_GENERATE_TOKEN_OUTPUTS_TOKEN: ${{ steps.generate-token.outputs.token }}
          GITHUB_EVENT_INPUTS_RUN_ID: ${{ github.event.inputs.run_id }}
